// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/alert.html", "js/collections/alerts", "js/models/alert"], function($, _, Backbone, template, cAlerts, mAlert) {
  var vAlerts;

  vAlerts = Backbone.View.extend({
    el: "#alerts",
    tagName: "div",
    initialize: function() {
      this.collection = new cAlerts();
      return this.collection.bind("change", this.render, this);
    },
    events: {
      "click .close": "close"
    },
    close: function(e) {
      var id, model;

      id = e.currentTarget.id;
      model = _.find(this.collection.models, function(model) {
        if (model.cid === id) {
          return model.set("hidden", true);
        }
      });
      return $(e.currentTarget).parent().remove();
    },
    add: function(type, message, code, debug) {
      var alert;

      alert = new mAlert({
        type: type,
        message: message,
        code: code
      });
      this.collection.add(alert);
      return this.render();
    },
    render: function() {
      var self;

      self = this.$el;
      self.html("");
      return _.each(this.collection.models, function(model) {
        var alert, cid;

        if (model.get("hidden") !== true) {
          cid = {
            cid: model.cid
          };
          alert = _.template(template, _.extend(model.toJSON(), cid));
          return self.append(alert);
        }
      });
    }
  });
  return new vAlerts();
});
