// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/elements.html"], function($, _, Backbone, template) {
  var vElements;

  vElements = Backbone.View.extend({
    el: "#elements",
    tagName: "div",
    initialize: function() {
      var me;

      $("#elements").hide();
      me = this;
      return Backbone.history.bind("all", function(route, router) {
        var page;

        page = window.location.hash;
        page = page.replace("!", "");
        page = page.replace("#", "");
        if (page === "core" || page === "earth" || page === "mind" || page === "voice" || page === "self") {
          return me.open(page);
        }
      });
    },
    events: {
      "click #close": "close",
      hashchange: "open",
      "click ul#sections li a": "select"
    },
    select: function(e) {
      var id;

      id = e.currentTarget.id;
      $(".info").hide();
      return $(".info#" + id).show();
    },
    close: function() {
      return $("#elements").hide();
    },
    open: function(element) {
      $(".info").hide();
      $(".element#" + element + " div.info").first().show();
      $(".element").hide();
      $(".element#" + element).show();
      return $("#elements").show();
    },
    render: function() {
      var compiled, data;

      data = {};
      compiled = _.template(template, data);
      this.$el.html(compiled);
      return compiled;
    }
  });
  return vElements;
});
