// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone", "text!html/footer.html", "js/views/login"], function($, _, Backbone, template, vLogin) {
    var view;

    view = Backbone.View.extend({
      el: "#footer",
      tagName: "footer",
      initialize: function() {
        return this.render();
      },
      render: function() {
        var compiled, data, options;

        data = {};
        compiled = _.template(template, data);
        this.$el.html(compiled);
        options = {};
        options.el = "#auth-footer";
        this.login = new vLogin(options);
        return compiled;
      }
    });
    return view;
  });

}).call(this);
