// Generated by CoffeeScript 1.6.2
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

define(["jquery", "underscore", "backbone", "text!html/header.html", "js/views/login"], function($, _, Backbone, template, vLogin) {
  var view;

  view = Backbone.View.extend({
    el: "#header",
    tagName: "header",
    initialize: function(options) {
      return this.render(options);
    },
    subdomains: ['docs', 'wiki', 'internal', 'agency'],
    render: function(options) {
      var compiled, data, _ref;

      data = {};
      compiled = _.template(template, data);
      this.$el.html(compiled);
      $('nav').hide();
      if (_ref = options.subdomain, __indexOf.call(this.subdomains, _ref) >= 0) {
        $('nav#' + options.subdomain).show();
        $('span#slogan').html(options.subdomain);
      } else {
        $('nav#www').show();
        $('span#slogan').html('');
      }
      this.login = new vLogin();
      return compiled;
    }
  });
  return view;
});
