// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/header.html", "js/views/login"], function($, _, Backbone, template, vLogin) {
  var view;

  view = Backbone.View.extend({
    el: "#header",
    tagName: "header",
    initialize: function() {
      return this.render();
    },
    render: function() {
      var compiled, data, subdomain;

      data = {};
      compiled = _.template(template, data);
      this.$el.html(compiled);
      $('nav').hide();
      subdomain = 'www';
      if (subdomain === 'agency') {
        $('nav#agency').show();
        $('span#slogan').html('Agency');
      } else if (subdomain === 'wiki') {
        $('nav#wiki').show();
        $('span#slogan').html('Wiki');
      } else {
        $('nav#www').show();
      }
      this.login = new vLogin();
      return compiled;
    }
  });
  return view;
});
