// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/stream/history.html", "js/collections/history", "text!html/items/post.html", "text!html/items/user.html", "text!html/items/org.html", "js/models/types", "js/models/session"], function($, _, Backbone, template, cHistory, tPost, tUser, tOrg, mTypes, mSession) {
  var vHistory;

  vHistory = Backbone.View.extend({
    className: "history",
    initialize: function() {
      return Backbone.Events.trigger("sidebar", "default");
    },
    render: function() {
      var compiled, data, h, self;

      self = this;
      data = {};
      compiled = _.template(template, data);
      this.$el.html(compiled);
      h = new cHistory({
        page: 0,
        limit: 20
      });
      return h.fetch({
        success: function(collection, response) {
          return self.display(response);
        },
        error: function(collection, response) {
          if (response.status === 404) {
            return self.$el.html('History was not found');
          } else {
            return Backbone.Events.trigger("alert", {
              type: "error",
              message: "History could not be loaded",
              response: response,
              location: "views/history",
              action: "read"
            });
          }
        }
      });
    },
    display: function(collection) {
      var $history, self;

      self = this;
      $history = $("div#history");
      return _.each(collection, function(obj, key) {
        var compiled, element, owner, type;

        if (!_.isUndefined(obj.post)) {
          type = obj.meta.type;
          element = mTypes.get_parent(type);
          owner = obj.meta.user_id === mSession.get("user_id");
          compiled = _.template(tPost, {
            address: obj.user.address[0],
            meta: obj.meta,
            post: obj.post,
            stats: obj.stats,
            user: obj.user.user,
            element: element,
            owner: owner,
            pic: self.pic,
            format_date: self.format_date
          });
        }
        if (!_.isUndefined(obj.user) && !_.isUndefined(obj.address)) {
          compiled = _.template(tUser, {
            user: obj.user,
            stats: obj.stats,
            address: obj.address,
            pic: self.pic,
            format_date: self.format_date
          });
        }
        if (!_.isUndefined(obj.org)) {
          compiled = _.template(tOrg, {
            org: obj.org,
            stats: obj.stats,
            address: obj.address[0],
            pic: self.pic
          });
        }
        if (!_.isUndefined(compiled)) {
          return $history.append(compiled);
        }
      });
    }
  });
  return vHistory;
});
