// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone", "auth", "text!html/login.html", "text!html/logout.html", "text!html/forgot.html", "text!html/password.html", "js/models/session", "js/views/alerts", "js/models/email"], function($, _, Backbone, auth, tLogin, tLogout, tForgot, tPassword, mSession, vAlerts, mEmail) {
    var view;

    view = Backbone.View.extend({
      el: "#login",
      tagName: "div",
      initialize: function() {
        _.bindAll(this);
        this.bind("login", this.session);
        return this.render();
      },
      events: {
        "click #auth": "login",
        "click #logout": "logout",
        "click #forgot": "forgot",
        "click #cancel": "cancel",
        "click #send": "send"
      },
      login: function() {
        var self;

        this.model = mSession;
        Backbone.BasicAuth.set($("input#email").val(), $("input#password").val());
        self = this;
        return this.model.save({}, {
          success: function(model, response) {
            return self.trigger("login", response);
          },
          error: function(model, response) {
            return Backbone.Events.trigger({
              response: response,
              location: "views/login",
              action: "login",
              type: "error"
            });
          }
        });
      },
      logout: function() {
        localStorage.removeItem("user");
        mSession.clear();
        this.render();
        return vAlerts.add("complete", "You have been logged out successfully.", "1", "");
      },
      forgot: function() {
        var compiled;

        compiled = _.template(tForgot, {});
        this.$el.html(compiled);
        return compiled;
      },
      cancel: function() {
        return this.render();
      },
      form: function() {
        var output;

        output = {};
        output.email = $("#email").val();
        output.password = $("#password").val();
        return output;
      },
      /* Email
      	  send: ->
      	    message = _.template(tPassword, 
      	      password: 123
      	      email: $("#email").val()
      	    )	 
      	    1
      		email = new mEmail(
      		  recipient_email: $("#email").val()
      		  subject: "Your Phourus Password"
      		  message: message
      		)
      				email.save
      		  success: ->
      		
      		  error: ->
      		    vAlerts.add "message", "Password could not be sent.", "1", ""
      */

      render: function() {
        var compiled;

        compiled = _.template(tLogin, {});
        this.$el.html(compiled);
        return compiled;
      },
      session: function(response) {
        var data, output, session;

        session = JSON.stringify(response);
        localStorage.setItem("session", session);
        data = localStorage.getItem("session");
        output = $.parseJSON(data);
        mSession.set(output);
        return this.render();
      }
    });
    return view;
  });

}).call(this);
