// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "auth", "text!html/login.html", "text!html/logout.html", "js/models/login", "js/models/session", "js/models/settings"], function($, _, Backbone, auth, tLogin, tLogout, mLogin, mSession, mSettings) {
  var view;

  view = Backbone.View.extend({
    tagName: "div",
    initialize: function(options) {
      _.bindAll(this);
      mSession.on("change", this.render);
      return this.render();
    },
    events: {
      "click .login": "login",
      "click .logout": "logout",
      "click .me": "me"
    },
    render: function() {
      var compiled, data;

      data = mSession.attributes;
      if (mSession.validate()) {
        compiled = _.template(tLogout, {
          data: data
        });
      } else {
        compiled = _.template(tLogin, {
          data: data
        });
      }
      this.$el.html(compiled);
      return compiled;
    },
    /* LOGIN
    */

    login: function() {
      var email, id, model, password, self;

      self = this;
      $("#mask").show();
      id = this.el.id;
      email = $("#" + id + " input.email").val();
      password = $("#" + id + " input.password").val();
      Backbone.BasicAuth.set(email, password);
      model = new mLogin();
      return model.save({}, {
        success: function(model, response) {
          var valid;

          $("#mask").hide();
          mSession.clear();
          mSession.set(response);
          valid = mSession.validate();
          if (valid === true) {
            return self.session;
          } else {
            return Backbone.Events.trigger("alert", {
              type: "message",
              message: "Login was unsuccessful, please try again",
              response: response,
              location: "views/login",
              action: "login"
            });
          }
        },
        error: function(model, response) {
          $("#mask").hide();
          return Backbone.Events.trigger("alert", {
            type: "error",
            message: "Login was unsuccessful, please try again",
            response: response,
            location: "views/login",
            action: "login"
          });
        }
      });
    },
    session: function() {
      localStorage.setItem("session", mSession.attributes);
      location.href = '/#!stream';
      return location.reload(false);
    },
    /* LOGOUT
    */

    logout: function() {
      localStorage.removeItem("session");
      location.href = '/#!home';
      return location.reload(false);
    },
    form: function() {
      var output;

      output = {};
      output.email = $(".email").val();
      output.password = $(".password").val();
      return output;
    },
    me: function() {
      return mSettings.set("mode", "me");
    },
    send: function() {
      /*
      message = _.template(tPassword, 
        password: 123
        email: $("#email").val()
      )	 
      
      email = new mEmail(
        recipient_email: $("#email").val()
        subject: "Your Phourus Password"
        message: message
      )
      email.save
        success: ->
      
        error: ->
          vAlerts.add "message", "Password could not be sent.", "1", ""
      */

    }
  });
  return view;
});
