// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/stream/notifications.html", "js/collections/notifications"], function($, _, Backbone, template, cNotifications) {
  var vNotifications;

  vNotifications = Backbone.View.extend({
    className: "notifications",
    initialize: function() {
      return Backbone.Events.trigger("sidebar", 'default');
    },
    render: function() {
      var collection, self;

      self = this;
      collection = new cNotifications({
        page: 0,
        limit: 40
      });
      return collection.fetch({
        success: function(model, response) {
          return self.$el.html(_.template(template, {
            data: response
          }));
        },
        error: function(model, response) {
          if (response.status === 404) {
            return self.$el.html('Notifications were not found');
          } else {
            return Backbone.Events.trigger("alert", {
              type: "error",
              message: "Notifications could not be loaded",
              response: response,
              location: "views/notifications",
              action: "read"
            });
          }
        }
      });
    }
  });
  return vNotifications;
});
