// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "js/models/user", "text!html/user.html", "text!html/404/user.html"], function($, _, Backbone, model, template, user404) {
  var vUser;

  vUser = Backbone.View.extend({
    el: "#user",
    tagName: "div",
    initialize: function() {},
    load: function(id) {
      var self;

      self = this;
      $("#mask").show();
      this.model = new model({
        id: id
      });
      return this.model.fetch({
        success: function() {
          self.render();
          return $("#mask").hide();
        },
        error: function(model, response) {
          $("#mask").hide();
          if (response.status === 404) {
            return self.$el.html(_.template(user404, {}));
          } else {
            return Backbone.Events.trigger("alert", {
              type: "error",
              message: "User could not be loaded",
              response: response,
              location: "views/user",
              action: "read"
            });
          }
        }
      });
    },
    render: function() {
      var compiled, data;

      Backbone.Events.trigger("sidebar", "profile");
      data = this.model.toJSON();
      compiled = _.template(template, {
        data: data
      });
      this.$el.html(compiled);
      return compiled;
    }
  });
  return vUser;
});
