// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/sidebar/form.html", "js/models/types", "js/views/sidebar/widgets/recent", "js/views/sidebar/widgets/create"], function($, _, Backbone, template, mTypes, vRecent, vCreate) {
  var view;

  view = Backbone.View.extend({
    el: "#sidebar",
    className: "form",
    initialize: function(options) {
      return this.render();
    },
    events: {
      "click #create": "select"
    },
    select: function(e) {
      var id;

      id = $("#posts").val();
      return window.location = "#add/" + id;
    },
    render: function() {
      var compiled, types;

      types = mTypes.attributes;
      compiled = _.template(template, {
        types: types
      });
      $(this.el).append(compiled);
      $("#posts").val(this.options.type);
      this.subviews("#recent", new vRecent({
        collapsible: true
      }));
      this.subviews("#create", new vCreate({
        collapsible: true
      }));
      return compiled;
    }
  });
  return view;
});
