// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/sidebar/single.html", "js/models/types", "js/views/sidebar/widgets/recent", "js/views/sidebar/widgets/create"], function($, _, Backbone, template, mTypes, vRecent, vCreate) {
  var view;

  view = Backbone.View.extend({
    el: "#sidebar",
    clasName: "single",
    initialize: function(options) {
      return this.render();
    },
    render: function() {
      var compiled, types;

      types = mTypes.attributes;
      compiled = _.template(template, {
        types: types
      });
      $(this.el).append(compiled);
      this.subviews("#recent", new vRecent());
      this.subviews("#create", new vCreate());
      return compiled;
    }
  });
  return view;
});
