// Generated by CoffeeScript 1.6.2
define(["jquery", "backbone", "js/base/sync", "underscore"], function($, Backbone, sync, _) {
  var model;

  model = Backbone.Model.extend({
    sync: sync,
    serialize: function(obj) {
      var p, str;

      str = [];
      for (p in obj) {
        str.push(encodeURIComponent(p) + "=" + encodeURIComponent(obj[p]));
      }
      return str.join("&");
    }
  });
  return model;
});
