// Generated by CoffeeScript 1.6.2
define(["jquery", "backbone", "underscore", "js/models/headers"], function($, Backbone, _, mHeaders) {
  var _sync;

  _sync = Backbone.sync;
  return Backbone.sync = function(method, model, options) {
    options.headers = options.headers || {};
    _.extend(options.headers, mHeaders.attributes);
    if (method === 'create' || method === 'update') {
      options.headers["Content-Type"] = "application/x-www-form-urlencoded";
      options.data = $.param(model.attributes);
    }
    return _sync(method, model, options);
  };
});
