// Generated by CoffeeScript 1.6.2
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define(["jquery", "backbone", "underscore", "js/collections/widgets"], function($, Backbone, _, cWidgets) {
    var view;

    view = Backbone.View.extend({
      /* CLEAR
      */

      clear: function() {
        return $(this.el).empty();
      },
      /* SUBVIEWS
      */

      subviews: function(selector, view) {
        var selectors;

        selectors = void 0;
        if (_.isObject(selector)) {
          selectors = selector;
        } else {
          selectors = {};
          selectors[selector] = view;
        }
        if (!selectors) {
          return;
        }
        return _.each(selectors, (function(view, selector) {
          return view.setElement(this.$(selector)).render();
        }), this);
      },
      /* PAGES
      */

      page: function(params) {
        var module, page, posts, self, users;

        params.el = "#widgets";
        page = params.page;
        self = this;
        if (this.extra(page) === true) {
          module = 'govs';
          require(["js/modules/orgs/extras/" + module + "/" + page], function(view) {
            var v;

            return v = new view(params);
          });
        } else {
          posts = ['checklist', 'calculator', 'matters', 'subjects', 'questions', 'answers', 'debates', 'bills', 'votes', 'beliefs', 'quotes', 'timeline'];
          users = ['employees', 'executives', 'teachers', 'students', 'citizens', 'reps', 'leaders', 'members'];
          if (__indexOf.call(posts, page) >= 0) {
            page = 'posts';
          }
          if (__indexOf.call(users, page) >= 0) {
            page = 'users';
          }
          require(["js/modules/orgs/shared/" + page], function(view) {
            var v;

            return v = new view(params);
          });
        }
        return page;
      },
      extra: function(page) {
        var extras, module;

        module = 'gov';
        extras = cWidgets[module];
        if (__indexOf.call(extras, page) >= 0) {
          return true;
        } else {
          return false;
        }
      },
      pic: function(type, id, ext) {
        return '/assets/pics/' + type + '/' + id + '.' + ext;
      }
    });
    return view;
  });

}).call(this);
