// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/widgets/facebook.html"], function($, _, Backbone, template) {
  var widget;

  widget = Backbone.View.extend({
    events: {
      "click a#temp": "test"
    },
    test: function() {
      return alert('test');
    },
    render: function() {
      var compiled, data;

      data = {};
      compiled = _.template(template, data);
      $(this.el).append(compiled);
      return compiled;
    }
  });
  return widget;
});
