// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
  var internal;

  return internal = {
    contacts: function(page) {
      var params, self;

      self = this;
      params = {};
      return require(["js/modules/internal/views/contacts/" + page], function(view) {
        view;        return self.toss(view, params);
      });
    },
    finance: function(page) {
      var params, self;

      self = this;
      params = {};
      return require(["js/modules/internal/views/finance/" + page], function(view) {
        view;        return self.toss(view, params);
      });
    },
    more: function(page) {
      var params, self;

      self = this;
      params = {};
      return require(["js/modules/internal/views/more/" + page], function(view) {
        view;        return self.toss(view, params);
      });
    },
    /* NEED TO EXTEND APPROUTER
    */

    toss: function(view, params) {
      var data;

      data = {
        view: view,
        params: params,
        id: "internal"
      };
      return Backbone.Events.trigger("module", data, this);
    }
  };
});
