// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
  var orgs;

  return orgs = {
    orgs: function(type, query) {
      var params, self, settings;

      self = this;
      if (!_.isUndefined(query)) {
        settings = query;
      }
      params = {
        section: "home",
        type: type,
        params: settings
      };
      return require(["js/modules/orgs/views/home"], function(view) {
        return self.toss(view, params);
      });
    },
    org: function(type, id, page) {
      var params, self;

      self = this;
      if (_.isUndefined(page) || page === "") {
        page = "about";
      }
      params = {
        id: id,
        type: type,
        page: page
      };
      return require(["js/modules/orgs/views/org"], function(view) {
        return self.toss(view, params);
      });
    },
    signup: function() {
      var params, self;

      self = this;
      params = {
        section: "signup",
        params: ""
      };
      return require(["js/modules/orgs/views/signup"], function(view) {
        return self.toss(view, params);
      });
    },
    admin: function() {
      var params, self;

      self = this;
      params = {
        section: "admin",
        params: ""
      };
      return require(["js/modules/orgs/views/admin"], function(view) {
        return self.toss(view, params);
      });
    }
  };
});
