// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
  var stream;

  return stream = {
    stream: function() {
      var params, self;

      self = this;
      params = {
        mode: "stream"
      };
      return require(["js/modules/stream/views/stream"], function(view) {
        return self.toss(view, params);
      });
    },
    post: function(id) {
      var params, self;

      self = this;
      params = {
        id: id
      };
      return require(["js/modules/stream/views/post"], function(view) {
        return self.toss(view, params);
      });
    },
    add: function(type) {
      var params, self;

      self = this;
      params = {
        mode: "add",
        type: type
      };
      return require(["js/modules/stream/views/form"], function(view) {
        return self.toss(view, params);
      });
    },
    edit: function(id) {
      var params, self;

      self = this;
      params = {
        mode: "edit",
        id: id
      };
      return require(["js/modules/stream/views/form"], function(view) {
        return self.toss(view, params);
      });
    },
    /* NEED TO EXTEND APPROUTER
    */

    toss: function(view, params) {
      var data;

      data = {
        view: view,
        params: params,
        id: "orgs"
      };
      return Backbone.Events.trigger("module", data, this);
    }
  };
});
