// Generated by CoffeeScript 1.6.2
define(function(require) {
  var $, Backbone, model, _;

  $ = require("jquery");
  _ = require("underscore");
  Backbone = require("Backbone");
  model = Backbone.Model.extend({
    initialize: function(options) {},
    url: "/rest/page/"
  });
  return model;
});
