// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/items/comment.html", "js/models/session"], function($, _, Backbone, template, mSession) {
  var view;

  view = Backbone.View.extend({
    className: "comment",
    initialize: function() {
      return _.bindAll(this);
    },
    events: {
      "click .edit": "edit",
      "click .delete": "delete",
      "click .confirm": "confirm",
      "click .save": "save",
      "click .cancel": "cancel"
    },
    edit: function(e) {
      var id;

      id = $(e.currentTarget).data("id");
      $(".item#" + id + " .actions div").hide();
      $(".item#" + id + " .actions div.actions-edit").show();
      $(".item#" + id + " .comment span").hide();
      return $(".item#" + id + " .comment textarea").show();
    },
    save: function(e) {
      return console.log($(e.currentTarget).data("id"));
    },
    "delete": function(e) {
      var id;

      id = $(e.currentTarget).data("id");
      $(".item#" + id + " .actions div").hide();
      return $(".item#" + id + " .actions div.actions-delete").show();
    },
    confirm: function(e) {
      return console.log($(e.currentTarget).data("id"));
    },
    cancel: function(e) {
      var id;

      id = $(e.currentTarget).data("id");
      $(".item#" + id + " .actions div").hide();
      $(".item#" + id + " .actions div.actions-admin").show();
      $(".item#" + id + " .comment span").show();
      return $(".item#" + id + " .comment textarea").hide();
    },
    render: function(options) {
      var compiled, created, d, modified, owner, self, session;

      self = this;
      this.model = options.toJSON();
      session = mSession.toJSON();
      owner = session.user_id === this.model.user.id;
      d = 0;
      modified = this.format_date(this.model.comment.modified, 'relative');
      created = this.format_date(this.model.comment.created, 'relative');
      if (created) {
        d = created;
      }
      if (modified) {
        d = 'Updated: ' + modified;
      }
      compiled = _.template(template, {
        comment: this.model.comment,
        session: session,
        pic: this.pic,
        user: this.model.user,
        owner: owner,
        date: d
      });
      $(this.el).html(compiled);
      $(".item .actions div").hide();
      $(".item .actions div.actions-admin").show();
      return this;
    }
  });
  return view;
});
