// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "js/models/settings", "text!html/stream/filter.html"], function($, _, Backbone, mSettings, tFilter) {
  var vFilter;

  vFilter = Backbone.View.extend({
    el: "#filter",
    tagName: "div",
    initialize: function() {
      return this.render();
    },
    events: {
      "change #sort": "selected",
      "change #direction": "selected",
      "change #type": "create",
      "click ul#mode li a": "mode",
      "click div.types input": "toggle"
    },
    toggle: function(e) {
      var target, types;

      target = e.currentTarget.id;
      types = "";
      $("div.types input:checked").each(function(index, value) {
        var id;

        id = $(this).attr("id");
        return types += id + ";";
      });
      console.log(types);
      types = types.slice(0, types.length - 1);
      return mSettings.set("types", types);
    },
    create: function(e) {
      var id, value;

      id = e.currentTarget.id;
      value = e.currentTarget.value;
      return window.location.hash = "#add/" + value;
    },
    selected: function(e) {
      var id, value;

      id = e.currentTarget.id;
      value = e.currentTarget.value;
      return mSettings.set(id, value);
    },
    mode: function(e) {
      var mode;

      mode = e.currentTarget.id;
      $("ul#mode li a").removeClass("selected");
      $("ul#mode li a#" + mode).addClass("selected");
      return mSettings.set("mode", mode);
    },
    render: function() {
      var compiled, data;

      data = {};
      compiled = _.template(tFilter, data);
      this.$el.html(compiled);
      return compiled;
    }
  });
  return vFilter;
});
