// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone", "text!html/stream/single/heading.html"], function($, _, Backbone, template) {
    var view;

    view = Backbone.View.extend({
      render: function() {
        var compiled, data;

        data = this.model.toJSON();
        ({
          events: {
            "click #plus": "thumbs",
            "click #minus": "thumbs"
          },
          thumbs: function(e) {
            var id;

            id = e.currentTarget.id;
            return console.log(id);
          }
        });
        compiled = _.template(template, {
          meta: data.meta,
          post: data.post,
          user: data.user,
          element: data.element,
          pic: this.pic
        });
        this.$el.html(compiled);
        return compiled;
      }
    });
    return view;
  });

}).call(this);
