// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/stream/post.html"], function($, _, Backbone, template) {
  var iPost;

  iPost = Backbone.View.extend({
    el: ".post",
    tagName: "div",
    initialize: function() {
      return this.render();
    },
    render: function() {
      var compiled, data;

      data = {};
      compiled = _.template(template, {
        data: data
      });
      this.$el.html(compiled);
      return compiled;
    }
  });
  return iPost;
});
