// Generated by CoffeeScript 1.6.2
define(function(require) {
  var $, Backbone, html, length, md, template, view, _;

  $ = require("jquery");
  _ = require("underscore");
  Backbone = require("backbone");
  md = require("mdown");
  template = require("text!html/pages/page.html");
  view = Backbone.View.extend({
    initialize: function(options) {},
    render: function() {
      var host, parts, self, source, subdomain;

      host = window.location.hostname;
      parts = host.split('.');
      subdomain = parts[0];
      $('body').addClass(subdomain);
      source = "mdown!md/" + subdomain + ("/" + this.options.path + ".md");
      self = this;
      Backbone.Events.trigger("sidebar", "pages");
      return require([source], function(template) {
        var compiled, match;

        match = template.slice(0, 15);
        if (match === html && template.length === length) {
          compiled = 'Not Found';
        } else {
          compiled = _.template(template, {});
        }
        self.$el.html(compiled);
        return compiled;
      });
    }
  });
  html = '<!DOCTYPE html>';
  length = 722;
  return view;
});
