// Generated by CoffeeScript 1.6.2
var $, Backbone, template, view, _;

define(function(require) {});

$ = require("jquery");

_ = require("underscore");

Backbone = require("backbone");

template = require("text!html/standard/standard.html");

view = Backbone.View.extend({
  initialize: function() {
    return this.render();
  },
  render: function() {
    var compiled, data;

    data = {};
    compiled = _.template(template, data);
    this.$el.html(compiled);
    return compiled;
  }
});

view;
