// Generated by CoffeeScript 1.6.2
define(function(require) {
  var $, Backbone, mPage, md, t404, template, view, _;

  $ = require("jquery");
  _ = require("underscore");
  Backbone = require("backbone");
  md = require("mdown");
  template = require("text!html/pages/page.html");
  t404 = require("text!html/404/general.html");
  mPage = require("js/modules/pages/models/page");
  view = Backbone.View.extend({
    initialize: function(options) {},
    render: function() {
      var host, parts, self, source, subdomain;

      self = this;
      host = window.location.hostname;
      parts = host.split('.');
      subdomain = parts[0];
      $('body').addClass(subdomain);
      source = "mdown!md/" + subdomain + ("/" + this.options.path + ".md");
      Backbone.Events.trigger("sidebar", "pages");
      return self.db();
    },
    db: function(subdomain) {
      var self;

      self = this;
      $("#mask").show();
      this.page = new mPage({
        subdomain: subdomain,
        path: this.options.path
      });
      return this.page.fetch({
        success: function(model, response) {
          $("#mask").hide();
          return self.$el.html(_.template(template, response));
        },
        error: function(model, response) {
          $("#mask").hide();
          if (response.status === 404) {
            return self.$el.html(_.template(t404, {
              auth: false
            }));
          } else {
            return Backbone.Events.trigger("alert", {
              type: "error",
              message: "Profile could not be loaded",
              response: response,
              location: "modules/standard/views/profile",
              action: "read"
            });
          }
        }
      });
    }
  });
  return view;
});
