// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($) {
  var model;

  model = Backbone.Model.extend({
    idAttribute: 'id',
    initialize: function(options) {
      return this.options = options;
    },
    url: function() {
      var url;

      url = "/rest/comments/?id=" + this.options.id;
      return url;
    },
    idAttribute: "id"
  });
  return model;
});
