// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($) {
  var model;

  model = Backbone.Model.extend({
    idAttribute: 'id',
    initialize: function(options) {
      return this.options = options;
    },
    methods: {
      'read': 'posts/?id=',
      'create': 'post/',
      'update': 'post/',
      'delete': 'post/'
    },
    sync: function(method, model, options) {
      options = options || {};
      options.url = 'rest/' + model.methods[method.toLowerCase()];
      if (!_.isUndefined(this.options.id)) {
        options.url += this.options.id;
      }
      return Backbone.sync.apply(this, arguments);
    }
  });
  return model;
});
