// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($) {
  var model;

  model = Backbone.Model.extend({
    idAttribute: 'id',
    initialize: function(options) {
      return this.options = options;
    },
    url: function() {
      var query, url;

      if (_.isUndefined(this.options.id)) {
        query = '';
      } else {
        query = this.options.id;
      }
      url = "/rest/post/" + query;
      return url;
    }
  });
  return model;
});
