// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone"], function($) {
    var model;

    model = Backbone.Model.extend({
      idAttribute: 'id',
      initialize: function(options) {
        return this.options = options;
      },
      url: function() {
        return "/rest/posts/?id=" + this.options.id;
      }
    });
    return model;
  });

}).call(this);
