// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/sidebar/widgets/create.html", "js/models/types", "js/models/settings"], function($, _, Backbone, template, mTypes, mSettings) {
  var view;

  view = Backbone.View.extend({
    tagName: "div",
    initialize: function(options) {
      this.options = {};
      this.options.collapsible = true;
      this.types = mTypes.attributes;
      return this.render();
    },
    events: {
      "click .button#add": "add",
      "click .button#edit": "edit"
    },
    add: function(e) {
      var location, type;

      type = $("select#types").val();
      if (!_.isUndefined(type)) {
        location = "#add/" + type;
        return window.location.hash = location;
      }
    },
    edit: function() {
      return mSettings.set("mode", "me");
    },
    render: function() {
      var compiled;

      compiled = _.template(template, {
        types: this.types,
        collapsible: this.options.collapsible
      });
      $(this.el).append(compiled);
      return compiled;
    }
  });
  return view;
});
