// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "js/views/alerts", "text!html/sidebar/widgets/recent.html", "js/collections/recent"], function($, _, Backbone, vAlerts, template, collection) {
  var view;

  view = Backbone.View.extend({
    tagName: "div",
    initialize: function(options) {
      var self;

      self = this;
      this.initialized = 0;
      this.options = {};
      this.options.collapsible = true;
      return this.collection = new collection({
        id: '1'
      });
      /*
      @collection.fetch
      	        success: ->
      	          self.initialized = 1
      	          self.render()
      	
      	        error: (collection, response) ->
      	          console.log response
      	          vAlerts.add response, "vStream", "filter", "error"
      */

    },
    render: function() {
      var compiled, data;

      if (this.initialized === 1) {
        data = this.collection.models;
        compiled = _.template(template, {
          data: data,
          collapsible: this.options.collapsible
        });
        $(this.el).append(compiled);
        return compiled;
      }
    }
  });
  return view;
});
