// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "js/models/session", "js/models/settings"], function($, _, Backbone, mSession, mSettings) {
  var collection;

  collection = Backbone.Collection.extend({
    initialize: function(options) {
      return this.options = options;
    },
    idAttribute: "id",
    initialize: function(options) {
      return this.options = options;
    },
    url: function() {
      var query;

      query = '?' + this.serialize(this.options);
      return "/rest/clout/" + query;
    }
  });
  return collection;
});
