// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
  var collection;

  collection = Backbone.Collection.extend({
    initialize: function(params) {
      this.params = "?type=" + params.type;
      if (!_.isUndefined(params.state)) {
        this.params += "&state=" + params.state;
      }
      if (!_.isUndefined(params.zip)) {
        return this.params += "&zip=" + params.state;
      }
    },
    url: function() {
      var url;

      url = "/rest/orgs/" + this.params;
      return url;
    },
    idAttribute: "id"
  });
  return collection;
});
