// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
  var collection;

  collection = Backbone.Collection.extend({
    initialize: function(options) {
      return this.options = options;
    },
    url: function() {
      var url;

      url = "/rest/org/?" + this.query();
      return url;
    },
    query: function() {
      var query;

      query = '';
      if (!_.isUndefined(this.options.user_id)) {
        query = "user_id=" + this.options.user_id + "&";
      } else if (!_.isUndefined(this.options.id)) {
        query = "id=" + this.options.id;
      }
      if (!_.isUndefined(this.options.type)) {
        query += "type=" + this.options.type + "&";
      }
      if (!_.isUndefined(this.options.state)) {
        query += "state=" + this.options.state + "&";
      }
      if (!_.isUndefined(this.options.zip)) {
        query += "zip=" + this.options.state + "&";
      }
      return query;
    },
    idAttribute: "id"
  });
  return collection;
});
