// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "js/models/session", "js/models/settings"], function($, _, Backbone, mSession, mSettings) {
  var cPosts;

  cPosts = Backbone.Collection.extend({
    initialize: function(options) {
      return this.options = options;
    },
    url: function() {
      var url;

      url = "/rest/posts/?debug=false&sort=influence&direction=DESC&org_id=" + this.options.id + "&page=0&limit=10&types=" + this.options.types;
      return url;
    },
    idAttribute: "id"
  });
  return cPosts;
});
