// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "js/models/session", "js/models/settings"], function($, _, Backbone, mSession, mSettings) {
  var collection;

  collection = Backbone.Collection.extend({
    initialize: function(options) {
      return this.options = options;
    },
    url: function() {
      var url;

      url = "/rest/review/?org_id=" + this.options.id + "&page=" + this.options.page + "&limit=" + this.options.limit;
      return url;
    },
    idAttribute: "id"
  });
  return collection;
});
