// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/internal/home.html"], function($, _, Backbone, template) {
  var view;

  view = Backbone.View.extend({
    className: "home",
    initialize: function(options) {
      return this.render(options);
    },
    render: function(options) {
      var compiled, data;

      data = {};
      compiled = _.template(template, data);
      this.$el.html(compiled);
      return compiled;
    }
  });
  return view;
});
