// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/sidebar/default.html"], function($, _, Backbone, template) {
  var view;

  view = Backbone.View.extend({
    el: "#sidebar",
    className: "default",
    initialize: function(options) {
      return this.render();
    },
    render: function() {
      var compiled, data;

      data = {
        user_id: 1
      };
      compiled = _.template(template, data);
      $(this.el).append(compiled);
      return compiled;
    }
  });
  return view;
});
