// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/sidebar/map.html", "js/models/special", "js/models/types"], function($, _, Backbone, template, mSpecial, mTypes) {
  var view;

  view = Backbone.View.extend({
    el: "#sidebar",
    className: "map",
    initialize: function(options) {
      this.options = {};
      this.options.type = options.type;
      this.options.mode = "states";
      this.states = mTypes.states;
      return this.render();
    },
    events: {
      "click a": "select",
      "click button#zipcode": "zip"
    },
    select: function(e) {
      return Backbone.Events.trigger("location", e.currentTarget.id);
    },
    zip: function(e) {
      return Backbone.Events.trigger("location", $("input#zip").val());
    },
    render: function() {
      var self;

      self = this;
      this.model = new mSpecial(this.options);
      return this.model.fetch({
        success: function(model, response) {
          return self.display(response);
        },
        error: function(model, response) {
          return self.generic();
        }
      });
    },
    display: function(response) {
      var compiled;

      compiled = _.template(template, {
        data: response,
        states: this.states
      });
      $(this.el).append(compiled);
      return compiled;
    },
    generic: function() {
      var compiled;

      compiled = _.template(template, {
        data: this.states,
        states: this.states
      });
      $(this.el).append(compiled);
      return compiled;
    }
  });
  return view;
});
