// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/sidebar/orgs.html", "js/collections/widgets"], function($, _, Backbone, template, cWidgets) {
  var view;

  view = Backbone.View.extend({
    el: "#sidebar",
    className: "orgs",
    initialize: function(options) {
      this.options = options;
      return this.render();
    },
    events: {
      "click a": "select",
      "click button#zipcode": "zip"
    },
    select: function(e) {
      return Backbone.Events.trigger("location", e.currentTarget.id);
    },
    zip: function(e) {
      return Backbone.Events.trigger("location", $("input#zip").val());
    },
    render: function() {
      var compiled, data;

      data = {};
      data.id = this.options.id;
      data.module = this.options.type;
      data.views = cWidgets[this.options.org_type];
      data.type = this.options.org_type;
      compiled = _.template(template, {
        data: data
      });
      this.$el.html(compiled);
      this.options.type = '';
      return compiled;
    }
  });
  return view;
});
