// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/orgs/shared/about.html", "js/modules/orgs/models/org", "js/models/stats", "text!html/orgs/about/stats.html"], function($, _, Backbone, template, mOrg, mStats, tStats) {
  var widget;

  widget = Backbone.View.extend({
    initialize: function(options) {
      var self;

      this.options = options;
      self = this;
      this.model = new mOrg(options);
      return $("#mask").show();
    },
    render: function() {
      var self;

      self = this;
      return this.model.fetch({
        success: function() {
          $("#mask").hide();
          return self.display();
        },
        error: function(collection, response) {
          $("#mask").hide();
          return Backbone.Events.trigger("alert", {
            type: "error",
            message: "About page could not be loaded",
            response: response,
            location: "modules/orgs/shared/about",
            action: "read"
          });
        }
      });
    },
    display: function() {
      var compiled, data;

      data = this.options.org;
      compiled = _.template(template, {
        org: data.org,
        address: data.address[0],
        stats: data.stats
      });
      $(this.el).append(compiled);
      this.stats();
      return compiled;
    },
    stats: function() {
      var self;

      return self = this;
      /*
      model = new mStats({type: 'org', id: 1})
      model.fetch
        success: (model) ->
          ##compiled = _.template(tStats, {stats: model.attributes})
          ##$('div#stats.right').append compiled
      
        error: (collection, response) ->
          vAlerts.add response, "vAbout", "stats", "error"
      */

    }
  });
  return widget;
});
