// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone", "text!html/orgs/shared/clout.html", "js/modules/orgs/collections/clout"], function($, _, Backbone, template, cClout) {
    var widget;

    widget = Backbone.View.extend({
      initialize: function(options) {
        var self;

        self = this;
        options.id = 1;
        this.collection = new cClout(options);
        return this.collection.fetch({
          success: function() {
            return self.render();
          },
          error: function(collection, response) {
            return Backbone.Events.trigger({
              response: response,
              location: "modules/orgs/shared/clout",
              action: "read",
              type: "error"
            });
          }
        });
      },
      render: function() {
        var compiled, data;

        data = this.collection.models;
        console.log(data);
        compiled = _.template(template, {
          data: data
        });
        $(this.el).append(compiled);
        return compiled;
      }
    });
    return widget;
  });

}).call(this);
