// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/orgs/shared/clout.html", "js/modules/orgs/collections/clout", "text!html/404/clout.html"], function($, _, Backbone, template, cClout, clout404) {
  var widget;

  widget = Backbone.View.extend({
    initialize: function(options) {
      var params, self;

      self = this;
      params = {};
      params.org_id = options.id;
      this.collection = new cClout(params);
      $("#mask").show();
      return this.collection.fetch({
        success: function() {
          $("#mask").hide();
          return self.render();
        },
        error: function(collection, response) {
          $("#mask").hide();
          if (response.status === 404) {
            return $(self.el).append(_.template(clout404, {
              auth: false
            }));
          } else {
            return Backbone.Events.trigger("alert", {
              type: "error",
              message: "Clout could not be loaded",
              response: response,
              location: "modules/orgs/shared/clout",
              action: "read"
            });
          }
        }
      });
    },
    render: function() {
      var compiled, data;

      data = this.collection.models;
      console.log(data);
      compiled = _.template(template, {
        data: data
      });
      $(this.el).append(compiled);
      return compiled;
    }
  });
  return widget;
});
