// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "forms", "text!html/orgs/shared/contact.html"], function($, _, Backbone, forms, template, mOrg) {
  var widget;

  widget = Backbone.View.extend({
    initialize: function(options) {
      var self;

      self = this;
      this.options.id = 1;
      console.log(options);
      return this.render();
    },
    render: function() {
      var compiled, data, websites;

      data = this.options.org;
      websites = [
        {
          label: "www",
          url: "www.phourus.com"
        }, {
          label: "wiki",
          url: "wiki.phourus.com"
        }, {
          label: "dev",
          url: "dev.phourus.com"
        }
      ];
      compiled = _.template(template, {
        org: data.org,
        address: data.address[0],
        id: data.id,
        websites: websites
      });
      $(this.el).append(compiled);
      this.form();
      return compiled;
    },
    form: function() {
      var container, form, schema;

      this.model = new Backbone.Model();
      form = {
        name: "Text",
        email: "Text",
        phone: "Text",
        message: "Text"
      };
      this.model.set("form", form);
      if (this.model.get("form") === false) {
        return;
      }
      schema = this.model.get("form");
      _.extend(this.model, {
        schema: schema
      });
      form = new Backbone.Form({
        schema: schema
      });
      form.render();
      container = this.$el.find("#fields");
      container.append(form.el);
      return $('.bbf-form').append('<button class="button green">Submit Form</button>');
    }
  });
  return widget;
});
