// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/orgs/shared/events.html", "js/modules/orgs/collections/events", "calendar"], function($, _, Backbone, template, cEvents, calendar) {
  var widget;

  widget = Backbone.View.extend({
    initialize: function(options) {
      return this.collection = cEvents;
    },
    render: function() {
      var compiled, data, editable, events, header;

      data = {};
      compiled = _.template(template, data);
      $(this.el).append(compiled);
      header = {};
      header.left = 'prev,next today';
      header.center = 'title';
      header.right = 'month,basicWeek,basicDay';
      editable = true;
      events = cEvents;
      console.log(events);
      $("#calendar").fullCalendar({
        header: header,
        editable: true,
        events: events
      });
      return compiled;
    }
  });
  return widget;
});
