// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone", "text!html/widgets/posts.html", "js/modules/orgs/collections/posts", "js/views/alerts", "js/models/types", "text!html/stream/post.html"], function($, _, Backbone, template, cPosts, vAlerts, mTypes, tPost) {
    var widget;

    widget = Backbone.View.extend({
      initialize: function(options) {
        var self;

        self = this;
        options.types = options.page;
        this.collection = new cPosts(options);
        return this.collection.fetch({
          success: function() {
            return self.render();
          },
          error: function(collection, response) {
            return Backbone.Events.trigger({
              response: response,
              location: "modules/orgs/shared/posts",
              action: "read",
              type: "error"
            });
          }
        });
      },
      render: function() {
        var self;

        self = this;
        _.each(this.collection.models, function(model) {
          var data;

          data = model.toJSON();
          data.meta.element = mTypes.get_parent(data.meta.type);
          return $(self.el).append(_.template(tPost, {
            post: data.post,
            meta: data.meta,
            address: data.address,
            stats: data.stats,
            user: data.user
          }));
        });
        return this.$el;
      }
    });
    return widget;
  });

}).call(this);
