// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone", "text!html/widgets/posts.html", "js/modules/orgs/collections/reviews", "js/views/alerts", "js/models/types", "text!html/orgs/shared/review.html"], function($, _, Backbone, template, cReviews, vAlerts, mTypes, tReview) {
    var widget;

    widget = Backbone.View.extend({
      initialize: function(options) {
        var self;

        self = this;
        options.id = 1;
        options.page = 1;
        options.limit = 10;
        this.collection = new cReviews(options);
        return this.collection.fetch({
          success: function() {
            return self.render();
          },
          error: function(collection, response) {
            return Backbone.Events.trigger({
              response: response,
              location: "modules/orgs/shared/reviews",
              action: "read",
              type: "error"
            });
          }
        });
      },
      render: function() {
        var self;

        self = this;
        _.each(this.collection.models, function(model) {
          var review;

          review = model.toJSON();
          return $(self.el).append(_.template(tReview, {
            data: review,
            pic: self.pic
          }));
        });
        return this.$el;
      }
    });
    return widget;
  });

}).call(this);
