// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone", "text!html/orgs/shared/posts.html", "js/modules/orgs/collections/community", "js/views/alerts", "js/models/types", "text!html/orgs/shared/users.html", "text!html/orgs/shared/user.html"], function($, _, Backbone, template, cCommunity, vAlerts, mTypes, tUsers, tUser) {
    var widget;

    widget = Backbone.View.extend({
      initialize: function(options) {
        var params, self;

        self = this;
        params = {};
        params.org_id = options.id;
        params.type = options.page.slice(0, -1);
        params.mode = 'full';
        this.collection = new cCommunity(params);
        return this.collection.fetch({
          success: function() {
            return self.render();
          },
          error: function(collection, response) {
            return Backbone.Events.trigger({
              response: response,
              location: "modules/orgs/shared/users",
              action: "read",
              type: "error"
            });
          }
        });
      },
      render: function() {
        var compiled, self;

        self = this;
        compiled = _.template(tUsers, '');
        $(self.el).append(compiled);
        _.each(this.collection.models, function(model) {
          var user;

          user = model.toJSON();
          user.influence = 48;
          return $(self.el).append(_.template(tUser, {
            user: user,
            pic: self.pic
          }));
        });
        return this.$el;
      }
    });
    return widget;
  });

}).call(this);
