// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/orgs/shared/posts.html", "js/modules/orgs/collections/community", "js/views/alerts", "js/models/types", "text!html/orgs/shared/users.html", "text!html/items/user.html", "text!html/404/users.html"], function($, _, Backbone, template, cCommunity, vAlerts, mTypes, tUsers, tUser, users404) {
  var widget;

  widget = Backbone.View.extend({
    initialize: function(options) {
      var self;

      self = this;
      this.params = {};
      this.params.org_id = options.id;
      this.params.type = options.page.slice(0, -1);
      this.params.mode = 'full';
      return $("#mask").show();
    },
    render: function() {
      var self;

      self = this;
      this.collection = new cCommunity(this.params);
      return this.collection.fetch({
        success: function() {
          $("#mask").hide();
          return self.display();
        },
        error: function(collection, response) {
          $("#mask").hide();
          if (response.status === 404) {
            return self.$el.html(_.template(users404, {
              auth: false
            }));
          } else {
            return Backbone.Events.trigger("alert", {
              type: "error",
              message: "Users could not be loaded",
              response: response,
              location: "modules/orgs/shared/users",
              action: "read"
            });
          }
        }
      });
    },
    display: function() {
      var compiled, l, self;

      console.log('hey');
      self = this;
      l = this.collection.models.length;
      compiled = _.template(tUsers, '');
      $(self.el).append(compiled);
      if (l === 0) {
        $(self.el).append('<h3 style="text-align: center;margin: 0px; padding: 0px">No users were found based on your criteria</h3>');
      }
      _.each(this.collection.models, function(model) {
        var o;

        o = model.toJSON();
        return self.$el.append(_.template(tUser, {
          user: o.user,
          stats: o.stats,
          address: o.address,
          pic: self.pic,
          format_date: self.format_date
        }));
      });
      return this.$el;
    }
  });
  return widget;
});
