// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "js/models/session"], function($, _, Backbone, mSession) {
  var collection;

  collection = Backbone.Collection.extend({
    initialize: function(options) {
      return this.options = options;
    },
    url: function() {
      var query, url, user_id;

      user_id = mSession.auth();
      query = '';
      if (!_.isUndefined(this.options.limit)) {
        query += '&limit=' + this.options.limit;
      }
      if (!_.isUndefined(this.options.page)) {
        query += '&page=' + this.options.page;
      }
      url = "/rest/notifications/?user_id=" + user_id + query;
      return url;
    },
    idAttribute: "id"
  });
  return collection;
});
