// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
    var collection, common, config;

    common = ['about', 'social', 'reviews', 'clout', 'events', 'contact'];
    collection = {
      company: {
        posts: ['checklist', 'calculator', 'matters'],
        community: ['executives', 'employees'],
        info: common,
        extra: ['commerce', 'org', 'jobs']
      },
      gov: {
        posts: ['debates', 'bills', 'votes'],
        community: ['reps', 'citizens'],
        info: common,
        extra: ['climate', 'demographics', 'financial', 'budget', 'projects', 'regions', 'purchasing', 'org']
      },
      group: {
        posts: ['beliefs', 'quotes', 'timeline'],
        community: ['leaders', 'members'],
        info: common,
        extra: ['org', 'donate']
      },
      school: {
        posts: ['subjects', 'questions', 'answers'],
        community: ['teachers', 'students'],
        info: common,
        extra: ['org', 'curriculum']
      }
    };
    config = function(module, page) {
      var mod, out;

      mod = collection[module];
      return out = mod[page];
    };
    return collection;
  });

}).call(this);
