// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
  var model;

  model = Backbone.Model.extend({
    initialize: function(options) {
      return this.options = options;
    },
    url: function() {
      var query, url;

      console.log(this.options);
      if (!_.isUndefined(this.options.id)) {
        query = "?id=" + this.options.id;
      }
      url = "/rest/orgs/" + query;
      return url;
    },
    idAttribute: "id"
  });
  return model;
});
