// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
  var model;

  model = Backbone.Model.extend({
    defaults: {
      id: 1,
      name: "Phourus LLC",
      twitter: "",
      facebook: "",
      linkedin: ""
    }
  });
  return model;
});
