// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "marionette"], function($, _, Backbone, marionette, init) {
  var controller, router;

  router = Backbone.Marionette.AppRouter.extend({
    controller: controller,
    initialize: function(options) {
      return this.bind('route', this.track);
    },
    appRoutes: {
      "contacts/:page": "contacts",
      "finance/:page": "finance",
      "more/:page": "more"
    }
  });
  controller = {
    contacts: function(page) {
      var params, self;

      self = this;
      params = {};
      return require(["js/modules/internal/views/contacts/" + page], function(view) {
        return self.toss(view, params);
      });
    },
    finance: function(page) {
      var params, self;

      self = this;
      params = {};
      return require(["js/modules/internal/views/finance/" + page], function(view) {
        return self.toss(view, params);
      });
    },
    more: function(page) {
      var params, self;

      self = this;
      params = {};
      return require(["js/modules/internal/views/more/" + page], function(view) {
        return self.toss(view, params);
      });
    },
    toss: function(view, params) {
      var data;

      data = {
        view: view,
        params: params,
        id: "internal"
      };
      return Backbone.Events.trigger("module", data, this);
    }
  };
  return new router({
    controller: controller
  });
});
