// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "marionette"], function($, _, Backbone, marionette) {
  var router;

  return router = Backbone.Marionette.AppRouter.extend({
    initialize: function(options) {
      return this.bind('route', this.track);
    },
    appRoutes: {
      "contacts/:page": "contacts",
      "finance/:page": "finance",
      "more/:page": "more"
    }
  });
});
