// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "marionette"], function($, _, Backbone, marionette, init) {
  var controller, router;

  router = Backbone.Marionette.AppRouter.extend({
    controller: controller,
    initialize: function(options) {
      return this.bind('route', this.track);
    },
    appRoutes: {
      "internal": "home"
    }
  });
  controller = {
    home: function() {
      var params, self;

      self = this;
      params = {
        mode: "stream"
      };
      return require(["js/modules/internal/views/home"], function(view) {
        return self.toss(view, params);
      });
    },
    toss: function(view, params) {
      var data;

      data = {
        view: view,
        params: params,
        id: "stream"
      };
      return Backbone.Events.trigger("module", data, this);
    }
  };
  return new router({
    controller: controller
  });
});
