// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "marionette"], function($, _, Backbone, marionette) {
  var controller, router;

  router = Backbone.Marionette.AppRouter.extend({
    controller: controller,
    appRoutes: {
      "pages": "pages",
      "page/*path": "page"
    }
  });
  controller = {
    slug: "pages",
    path: function() {
      return "modules/{{@slug}}/";
    },
    pages: function() {
      var params, self;

      self = this;
      params = {
        params: settings
      };
      return require(["pages"], function(view) {
        return self.toss(view, params);
      });
    },
    page: function(path) {
      var params, self;

      self = this;
      params = {
        path: path
      };
      console.log(params);
      return require(["js/modules/pages/views/page"], function(view) {
        return self.toss(view, params);
      });
    },
    add: function() {
      var params, self;

      self = this;
      params = {
        mode: "add"
      };
      return require(["form"], function(view) {
        return self.toss(view, params);
      });
    },
    edit: function(id) {
      var params, self;

      self = this;
      params = {
        id: id,
        mode: "edit"
      };
      return require(["form"], function(view) {
        return self.toss(view, params);
      });
    },
    toss: function(view, params) {
      var data;

      data = {
        view: view,
        params: params
      };
      return Backbone.Events.trigger("module", data, this);
    }
  };
  return new router({
    controller: controller
  });
});
