// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "marionette"], function($, _, Backbone, marionette) {
  var router;

  return router = Backbone.Marionette.AppRouter.extend({
    initialize: function(options) {
      return this.bind('route', this.track);
    },
    appRoutes: {
      "": "homepage",
      "!home": "homepage",
      "!about": "about",
      "!contact": "contact",
      "terms": "terms",
      "privacy": "privacy",
      "!signup": "signup",
      "user/:id": "user",
      "!history": "history",
      "!notifications": "notifications"
    }
  });
});
