// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone", "marionette"], function($, _, Backbone, marionette, init) {
    var controller, router;

    router = Backbone.Marionette.AppRouter.extend({
      controller: controller,
      appRoutes: {
        "": "stream",
        "!stream": "stream",
        "!post/:id": "post",
        "add/:type": "add",
        "edit/:id": "edit"
      }
    });
    controller = {
      stream: function() {
        var params, self;

        self = this;
        params = {
          mode: "stream"
        };
        return require(["js/modules/stream/views/stream"], function(view) {
          return self.toss(view, params);
        });
      },
      post: function(id) {
        var params, self;

        self = this;
        params = {
          id: id
        };
        return require(["js/modules/stream/views/single"], function(view) {
          return self.toss(view, params);
        });
      },
      add: function(type) {
        var params, self;

        self = this;
        params = {
          mode: "add",
          type: type
        };
        return require(["js/modules/stream/views/form"], function(view) {
          return self.toss(view, params);
        });
      },
      edit: function(id) {
        var params, self;

        self = this;
        params = {
          mode: "edit",
          id: id
        };
        return require(["js/modules/stream/views/form"], function(view) {
          return self.toss(view, params);
        });
      },
      toss: function(view, params) {
        var data;

        data = {
          view: view,
          params: params,
          id: "stream"
        };
        return Backbone.Events.trigger("module", data, this);
      }
    };
    return new router({
      controller: controller
    });
  });

}).call(this);
