// Generated by CoffeeScript 1.6.2
require.config({
  baseUrl: "/app",
  urlArgs: "bust=" + (new Date()).getTime(),
  paths: {
    jquery: "lib/jquery",
    underscore: "lib/underscore",
    backbone: "lib/backbone",
    marionette: "lib/marionette",
    text: "lib/text",
    forms: "lib/forms",
    auth: "lib/auth",
    firefly: "lib/firefly",
    async: "lib/async",
    goog: "lib/goog",
    parser: "lib/parser",
    mdown: "lib/mdown",
    markdownConverter: 'lib/converter',
    calendar: "lib/calendar",
    analytics: "js/models/analytics",
    livereload: "js/models/livereload",
    storage: "lib/storage"
  },
  shim: {
    backbone: {
      deps: ["jquery", "underscore"],
      exports: "Backbone"
    },
    underscore: {
      exports: "_"
    },
    forms: {
      deps: ["backbone"],
      exports: "forms"
    },
    jquery: {
      exports: "$"
    },
    marionette: {
      deps: ["jquery", "underscore", "backbone"],
      exports: "Marionette"
    }
  }
});

define("init", function(require) {
  var $, Backbone, app, cInternal, cOrgs, cPages, cStandard, cStream, mHeaders, mSession, mView, marionette, options, rInternal, rOrgs, rPages, rStandard, rStream, vAlerts, vFooter, vHeader, vSidebar, _;

  $ = require("jquery");
  _ = require("underscore");
  Backbone = require("backbone");
  marionette = require("marionette");
  mSession = require("js/models/session");
  mView = require("js/models/view");
  mHeaders = require("js/models/headers");
  vAlerts = require("js/views/alerts");
  rStandard = require("js/routers/standard");
  rStream = require("js/routers/stream");
  rOrgs = require("js/routers/orgs");
  rInternal = require("js/routers/internal");
  rPages = require("js/routers/pages");
  cStandard = require("js/controllers/standard");
  cStream = require("js/controllers/stream");
  cOrgs = require("js/controllers/orgs");
  cInternal = require("js/controllers/internal");
  cPages = require("js/controllers/pages");
  new rPages({
    controller: cPages
  });
  new rStandard({
    controller: cStandard
  });
  new rStream({
    controller: cStream
  });
  new rOrgs({
    controller: cOrgs
  });
  new rInternal({
    controller: cInternal
  });
  vHeader = require("js/views/header");
  vSidebar = require("js/views/sidebar");
  vFooter = require("js/views/footer");
  Backbone.Collection = require("js/base/collection");
  Backbone.Model = require("js/base/model");
  Backbone.View = require("js/base/view");
  Backbone.Router = require("js/base/router");
  app = new Backbone.Marionette.Application();
  app.addRegions({
    content: "#content"
  });
  app.addInitializer(function(options) {
    var self;

    self = this;
    Backbone.Events.on("module", function(data) {
      var view;

      $("#content").removeClass('homepage');
      view = data.view;
      return app.content.show(new view(data.params));
    });
    Backbone.Events.on("alert", function(data) {
      if (data.type === "error") {
        console.log(data);
      }
      return vAlerts.add(data.type, data.message);
    });
    Backbone.Events.on("back", function(data) {
      return window.history.back();
    });
    Backbone.Events.on("token", function(data) {
      mHeaders.set("x-api-key", data.token);
      return mHeaders.set("from", data.user_id);
    });
    return Backbone.Events.on("map", function(data) {
      var dev;

      dev = false;
      if (dev !== true) {
        return require(["js/models/maps"], function(mMap) {
          var gmap, map;

          gmap = $.find("#gmap").length;
          if (gmap > 0) {
            map = new mMap(data);
            map.setElement($("#gmap"));
            map.render();
          }
          return 1;
        });
      }
    });
  });
  app.on("initialize:before", function(options) {
    return mSession.local();
  });
  app.on("initialize:after", function(options) {
    var admin, host, parts, subdomain;

    host = window.location.hostname;
    parts = host.split('.');
    subdomain = parts[0];
    this.subdomain = subdomain;
    admin = 0;
    if ((subdomain === 'wiki' || subdomain === 'internal') && admin !== 1) {
      alert("You must be an admin to access this page. Please log in with an Admin account if you wish to access this subdomain.");
      location.href = "http://www.phourus.local/";
    }
    options = {
      subdomain: this.subdomain
    };
    app.header = new vHeader(options);
    app.sidebar = new vSidebar(options);
    app.footer = new vFooter();
    Backbone.history = Backbone.history || new Backbone.History({});
    Backbone.history.start();
    /* VIEW TRACKING
    */

    return window.onhashchange = function() {
      return $('#alerts').html('');
      /*
      alert('change')
      view= new mView()
      view.save(
        success: ()->
          alert('success')
          
        error: ()->
          alert('fail') 
      )
      */

    };
  });
  app.on("start", function(options) {});
  options = {};
  app.start(options);
  return app;
});
