// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
  var model;

  model = Backbone.Model.extend({
    initialize: function(options) {
      return this.id = options.id;
    },
    urlRoot: function() {
      return "/rest/page/" + this.id;
    },
    defaults: {
      title: "Page not found",
      content: "Sorry, but the page you were looking for does not exist."
    }
  });
  return model;
});
