// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "js/views/alerts"], function($, _, Backbone, vAlerts) {
  var mRegister;

  mRegister = Backbone.Model.extend({
    urlRoot: "/rest/register",
    defaults: {},
    parse: function(response) {
      if (response.error === 1) {
        vAlerts.add("error", response.data, 1, response.debug);
        return false;
      }
      return response.data;
    }
  });
  return mRegister;
});
