// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
  var model;

  model = Backbone.Model.extend({
    initialize: function(options) {
      return this.options = options;
    },
    url: function() {
      var query, url;

      query = '';
      if (!_.isUndefined(this.options) && !_.isUndefined(this.options)) {
        query = this.options.id;
      }
      url = "/rest/user/" + query;
      return url;
    },
    idAttribute: "id"
  });
  return model;
});
