// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
  var model;

  model = Backbone.Model.extend({
    key: '1af42f7c7dd9677fce0aa420e3f8a051a481c96e'
  }, initialize(function(options) {
    return this.options = options;
  }), url(function() {
    return this.options;
  }));
  return model;
});
