// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
  var mEmail;

  mEmail = Backbone.Model.extend({
    url: "/rest/email",
    defaults: {
      sender_name: "Phourus.com",
      sender_email: "info@phourus.com",
      recipient_name: "",
      recipient_email: "",
      subject: "",
      message: ""
    }
  });
  return mEmail;
});
