// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
  var model;

  model = Backbone.Model.extend({
    idAttribute: 'id',
    url: function() {
      return "/rest/session";
    }
  });
  return model;
});
