// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
  var mSession;

  mSession = Backbone.Model.extend({
    urlRoot: "/rest/session",
    expired: function() {
      var expired, expires, now;

      expires = this.get("expires");
      now = this.now();
      console.log("Expires: " + expires + "     Now: " + now);
      expired = expires < now;
      return expired;
    },
    now: function() {
      var date, output;

      date = new Date().toISOString();
      output = date.replace("T", " ");
      output = output.split(".");
      return output[0];
    }
  });
  return new mSession();
});
