// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
  var mUser;

  mUser = Backbone.Model.extend({
    urlRoot: function() {
      return "/rest/user/";
    }
  });
  return mUser;
});
