// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
    var model;

    model = Backbone.Model.extend({
      urlRoot: function() {
        return "/rest/view/";
      }
    });
    return model;
  });

}).call(this);
