// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone", "text!html/orgs/heading.html"], function($, _, Backbone, template) {
    var view;

    view = Backbone.View.extend({
      initialize: function(options) {
        this.options = options;
        return this.render();
      },
      render: function() {
        var compiled, data;

        data = this.options;
        compiled = _.template(template, {
          id: data.id,
          org: data.org,
          address: data.address[0],
          stats: data.stats,
          pic: this.pic
        });
        this.$el.html(compiled);
        return compiled;
      }
    });
    return view;
  });

}).call(this);
