// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "marionette", "text!html/orgs/home.html", "text!html/items/org.html", "js/modules/orgs/collections/orgs", "js/views/sidebar", "text!html/404/orgs.html"], function($, _, Backbone, marionette, template, tOrg, cOrgs, vSidebar, orgs404) {
  /*      
  item = Backbone.Marionette.ItemView.extend(
  	template: iList
  )
  view = Backbone.Marionette.CompositeView.extend(
    itemView: item
    itemViewContainer: '#item'
    template: template
    collection: new cGovs(raw)    
  )
  view
  */

  var view;

  view = Backbone.View.extend({
    tagName: 'div',
    className: 'orgs',
    initialize: function(options) {
      var self;

      self = this;
      return this.options = options;
    },
    render: function() {
      var self;

      self = this;
      $("#mask").show();
      Backbone.Events.trigger("sidebar", {
        type: 'default',
        params: this.options
      });
      this.collection = new cOrgs({
        type: this.options.type
      });
      return this.collection.fetch({
        success: function() {
          $("#mask").hide();
          return self.display();
        },
        error: function(collection, response) {
          $("#mask").hide();
          return self.$el.html(_.template(orgs404, {}));
        }
      });
    },
    display: function() {
      var compiled, data, list, self;

      self = this;
      data = {
        type: this.options.type
      };
      compiled = _.template(template, data);
      $(this.el).html(compiled);
      list = this.$el.find('#list');
      _.each(this.collection.models, function(model) {
        var item;

        data = model.toJSON();
        item = _.template(tOrg, {
          org: data.org,
          stats: data.stats,
          address: data.address[0],
          pic: self.pic
        });
        return list.append(item);
      });
      Backbone.Events.trigger("map", this.collection.models);
      return compiled;
    }
  });
  return view;
});
