// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/orgs/org.html", "text!html/headings/org.html", "js/modules/orgs/models/org", "text!html/404/org.html"], function($, _, Backbone, template, tHeading, model, org404) {
  var view;

  view = Backbone.View.extend({
    initialize: function(options) {
      return this.options = options;
    },
    events: {
      "click .back": "back"
    },
    back: function() {
      return Backbone.Events.trigger("back", {});
    },
    render: function() {
      var params, self;

      self = this;
      this.model = new model({
        id: this.options.id
      });
      params = {
        org_type: this.options.type,
        page: this.options.page,
        id: this.options.id
      };
      Backbone.Events.trigger("sidebar", {
        type: 'orgs',
        params: params
      });
      return this.model.fetch({
        success: function() {
          return self.display();
        },
        error: function(model, response) {
          if (response.status === 404) {
            self.$el.html(_.template(org404, {}));
          }
          if (response.status === 503) {
            return Backbone.Events.trigger("alert", {
              type: "error",
              message: "Org could not be loaded",
              response: response,
              location: "modules/orgs/views/org",
              action: "read"
            });
          }
        }
      });
    },
    display: function() {
      var compiled, data, heading;

      data = this.model.toJSON();
      this.options.org = data;
      compiled = _.template(template, data);
      this.$el.html(compiled);
      heading = _.template(tHeading, {
        org: data.org,
        stats: data.stats,
        pic: this.pic
      });
      $(".heading").html(heading);
      this.page(this.options);
      return compiled;
    }
  });
  return view;
});
