// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone", "text!html/orgs/org.html", "js/modules/orgs/views/heading", "js/views/sidebar", "js/modules/orgs/models/org"], function($, _, Backbone, template, vHeading, vSidebar, model) {
    var view;

    view = Backbone.View.extend({
      initialize: function(options) {
        return this.options = options;
      },
      render: function() {
        var self;

        this.model = new model({
          id: this.options.id
        });
        Backbone.Events.trigger("sidebar", {
          type: 'orgs',
          org_type: this.options.type,
          page: this.options.page,
          id: this.options.id
        });
        self = this;
        return this.model.fetch({
          success: function() {
            return self.display();
          },
          error: function(model, response) {
            return Backbone.Events.trigger({
              response: response,
              location: "modules/orgs/views/org",
              action: "read",
              type: "error"
            });
          }
        });
      },
      display: function() {
        var compiled, data;

        data = this.model.toJSON();
        this.options.org = data;
        compiled = _.template(template, data);
        this.$el.html(compiled);
        this.subviews("#heading", new vHeading(data));
        this.page(this.options);
        return compiled;
      }
    });
    return view;
  });

}).call(this);
