// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/orgs/signup.html"], function($, _, Backbone, template) {
  var view;

  view = Backbone.View.extend({
    initialize: function() {},
    render: function() {
      var compiled, data;

      data = {};
      Backbone.Events.trigger("sidebar", "general");
      compiled = _.template(template, data);
      this.$el.html(compiled);
      return compiled;
    }
  });
  return view;
});
