// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/widgets/influence.html"], function($, _, Backbone, template) {
  var widget;

  widget = Backbone.View.extend({
    raw: {
      influence: 69,
      followers: 1432,
      following: 321,
      friends: 213,
      posts: 31,
      influence_posts: 42,
      influence_friends: 55
    },
    render: function() {
      var compiled, data;

      data = this.raw;
      compiled = _.template(template, {
        data: this.raw
      });
      $(this.el).append(compiled);
      return compiled;
    }
  });
  return widget;
});
