// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/widgets/maps.html"], function($, _, Backbone, template) {
  var widget;

  widget = Backbone.View.extend({
    render: function() {
      var compiled, data;

      data = {};
      compiled = _.template(template, data);
      $(this.el).append(compiled);
      return compiled;
    }
  });
  return widget;
});
