// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "forms", "text!html/standard/contact.html", "js/models/types", "js/modules/standard/models/contact"], function($, _, Backbone, forms, template, mTypes, mContact) {
  var view;

  view = Backbone.View.extend({
    className: "contact",
    initialize: function() {},
    render: function() {
      var compiled, container, data, schema;

      data = {};
      data.description = mTypes.description("contact");
      Backbone.Events.trigger("sidebar", "general");
      compiled = _.template(template, {
        data: data
      });
      this.$el.html(compiled);
      this.model = new mContact();
      schema = mTypes.schema('contact');
      _.extend(this.model, {
        schema: schema
      });
      this.form = new Backbone.Form({
        schema: schema,
        model: this.model
      });
      this.form.render();
      container = this.$el.find("#fields");
      container.append(this.form.el);
      return this;
    }
  });
  return view;
});
