// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone", "text!html/standard/help.html"], function($, _, Backbone, template) {
    var view;

    view = Backbone.View.extend({
      initialize: function() {
        return this.render();
      },
      render: function() {
        var compiled, data;

        data = {};
        compiled = _.template(template, data);
        this.$el.html(compiled);
        return compiled;
      }
    });
    return view;
  });

}).call(this);
