// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/standard/page.html", "js/modules/standard/models/page"], function($, _, Backbone, template, model) {
  var view;

  view = Backbone.View.extend({
    initialize: function(options) {
      var self;

      self = this;
      this.model = new model(options.page);
      return this.model.fetch({
        success: function() {
          return self.render();
        },
        error: function() {
          return self.render();
        }
      });
    },
    render: function() {
      var compiled;

      compiled = _.template(template, {
        data: this.model.toJSON()
      });
      this.$el.html(compiled);
      return compiled;
    }
  });
  return view;
});
