// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "underscore", "backbone", "forms", "text!html/standard/profile.html", "js/views/sidebar", "js/modules/standard/models/profile"], function($, _, Backbone, forms, template, vSidebar, mProfile) {
    var view;

    view = Backbone.View.extend({
      className: "profile",
      initialize: function(options) {},
      render: function() {
        var self;

        self = this;
        this.model = new mProfile({
          id: this.options.user
        });
        return this.model.fetch({
          success: function() {
            return self.display();
          },
          error: function(error, response) {
            return Backbone.Events.trigger({
              response: response,
              location: "modules/standard/views/profile",
              action: "read",
              type: "error"
            });
          }
        });
      },
      events: {
        "click ul.tabs a": "tab",
        "click #update_account": "expand"
      },
      expand: function() {
        if ($("#update").is(':hidden') === true) {
          $("#update").show();
          return $("#update_account").html("Hide Profile Information");
        } else {
          $("#update").hide();
          return $("#update_account").html("Edit Profile Information");
        }
      },
      tab: function(e) {
        var id;

        id = e.currentTarget.id;
        $(".view").hide();
        $(".view#view_" + id).show();
        $("ul.tabs li a").removeClass('selected');
        return $("ul.tabs li a#" + id).addClass('selected');
      },
      display: function() {
        var compiled, container, data, form, schema, totals;

        data = this.model.attributes;
        console.log(data);
        totals = {
          blogs: 6,
          links: 14,
          ideas: 1,
          checklist: '',
          calculator: '',
          matters: 3,
          subjects: 11,
          questions: 5,
          answers: 7,
          debates: 21,
          bills: 6,
          votes: 22,
          beliefs: 4,
          timeline: 2,
          quotes: 10
        };
        compiled = _.template(template, {
          user: data,
          pic: this.pic,
          totals: totals
        });
        this.$el.html(compiled);
        schema = {
          "website": "Text",
          "email": "Text",
          "phone": "Text"
        };
        form = new Backbone.Form({
          model: this.model,
          schema: schema
        });
        form.render();
        container = this.$el.find("#fields");
        container.append(form.el);
        Backbone.Events.trigger("sidebar", "profile");
        return compiled;
      }
    });
    return view;
  });

}).call(this);
