// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "text!html/standard/signup.html", "js/views/register"], function($, _, Backbone, template, vRegister) {
  var view;

  view = Backbone.View.extend({
    events: {
      "click .register": "register"
    },
    render: function() {
      var compiled, container, data;

      data = {};
      Backbone.Events.trigger("sidebar", "default");
      compiled = _.template(template, data);
      this.$el.html(compiled);
      this.register = new vRegister();
      this.form = this.register.render();
      container = this.$el.find("#fields");
      container.append(this.form);
      return this;
    },
    register: function(e) {
      return this.register.register(e);
    }
  });
  return view;
});
