// Generated by CoffeeScript 1.6.2
define(["jquery", "underscore", "backbone", "forms", "text!html/standard/signup.html", "text!html/email/signup.html", "js/modules/standard/models/user", "js/models/email", "js/models/types"], function($, _, Backbone, forms, template, tSignup, mUser, mEmail, mTypes) {
  var view;

  view = Backbone.View.extend({
    events: {
      "click #complete": "register"
    },
    render: function() {
      var compiled, container, data, schema;

      data = {};
      Backbone.Events.trigger("sidebar", "general");
      compiled = _.template(template, data);
      this.$el.html(compiled);
      this.model = new mUser();
      schema = mTypes.schema('signup');
      _.extend(this.model, {
        schema: schema
      });
      this.form = new Backbone.Form({
        schema: schema,
        model: this.model
      });
      this.form.render();
      container = this.$el.find("#fields");
      container.append(this.form.el);
      return this;
    },
    register: function() {
      var self;

      this.model = new mRegister(this.collect());
      self = this;
      return this.model.save({}, {
        success: function(model, response) {
          var data, email, message;

          message = "Registration was successful. Check your email for your password and account information.";
          message += "<br /><strong>Password:</strong> " + response.password;
          vAlerts.add("complete", message, "1", "");
          data = self.collect();
          message = _.template(tSignup, data);
          email = new mEmail({
            recipient_name: data.first + " " + data.last,
            recipient_email: data.email,
            subject: "Your Phourus Password",
            message: message
          });
          return email.save({
            success: function() {},
            error: function(error, response) {
              return Backbone.Events.trigger("alert", {
                type: "message",
                message: "Registration was successful, but there was an error sending your email. Please contact us if you do not receive your password.",
                response: response,
                location: "modules/standard/views/signup",
                action: "save"
              });
            }
          });
        },
        error: function(model, response) {
          console.log(model);
          return console.log(response);
        }
      });
    },
    collect: function() {
      var me, output;

      me = this;
      output = {
        first: $("#first").val(),
        last: $("#last").val(),
        email: $("#email").val(),
        password: $("#password").val()
      };
      return output;
    }
  });
  return view;
});
